### ISSUE TITLE
修改的不错啊! 赞赞赞 :+1:

### ISSUE THREAD

**Issue by BruceZhaoR** [binism/binism.github.io#1]
我知道你肯定在修改的时候骂过我, 因为我完全没有想到会当模板给别人用, 所以想改什么就直接去源码修改,而且没有变量化, 所以你会发现一个又一个bug.. 我简单的浏览了一下你的博客, 也写下了一些评论与修改意见. draft里面的model是post的模板, 每次写直接copy改一下就能用了. 这个模板还能放html5幻灯片,详细用法请见hux的, 我亲测过, 因为不是自己做的, 所有没有放上去.

**Comment by binism** [comment]
修改其实也没有花费太大的功夫，我就post上去，看看哪里不对，然后再改。感谢！
